### ISSUE TITLE
EXC_BAD_ACCESS on Thread class

### ISSUE THREAD

**Issue by brunophilipe** [DoubleSha/BitcoinSwift#15]
Hey! Thanks for the awesome project!

I've been trying to use the BitcoinSwift in a personal project, but whenever I attempt to use anything involving the `PeerConnection` class, which uses the `Thread` class, I keep getting `EXC_BAD_ACCESS` errors in a background thread.

Inspecting the `runLoop` instance variable outputs this:
```
Printing description of self.runLoop:
▿ Optional(<CFRunLoop 0x7fd03a4ae530 [0x10ee647b0]>{wakeup port = 0x430b, stopped = false, ignoreWakeUps = false, 
current mode = kCFRunLoopDefaultMode,
common modes = <CFBasicHash 0x7fd03a4ae5f0 [0x10ee647b0]>{type = mutable set, count = 1,
entries =>
	2 : <CFString 0x10ee84b40 [0x10ee647b0]>{contents = "kCFRunLoopDefaultMode"}
}
,
common mode items = <CFBasicHash 0x7fd03a4a5cd0 [0x10ee647b0]>{type = mutable set, count = 2,
entries =>
	0 : <CFRunLoopSource 0x7fd03a4a24a0 [0x10ee647b0]>{signalled = No, valid = Yes, order = 0, context = <CFArray 0x7fd03a4a5b00 [0x10ee647b0]>{type = mutable-small, count = 2, values = (
	0 : <CFReadStream 0x7fd03a618c30>{<SocketStream 0x7fd03a618c30>{flags = 0x7fd03a62eaa8, read = 0x7fd03a618c30, write = 0x7fd03a617080, socket = <CFSocket 0x7fd03a75d610 [0x10ee647b0]>{valid = Yes, type = 1, socket = 13, socket set count = 2,
    callback types = 0xd, callout = _ZN12SocketStream22_SocketCallBack_streamEP10__CFSocketmPK8__CFDataPKvPv (0x110e10246), source = 0x7fd03a755c60,
    run loops = <CFArray 0x7fd03a5ed390 [0x10ee647b0]>{type = mutable-small, count = 2, values = (
	0 : <0x7fd03a71a780>
	1 : <0x7fd03a4ae530>
)},
    context = <SocketStream@0x7fd03a62e9b0> { fd 13 }}, properties = 0x7fd03a621b70 }}
	1 : <CFWriteStream 0x7fd03a617080>{<SocketStream 0x7fd03a617080>{flags = 0x7fd03a62eaa8, read = 0x7fd03a618c30, write = 0x7fd03a617080, socket = <CFSocket 0x7fd03a75d610 [0x10ee647b0]>{valid = Yes, type = 1, socket = 13, socket set count = 2,
    callback types = 0xd, callout = _ZN12SocketStream22_SocketCallBack_streamEP10__CFSocketmPK8__CFDataPKvPv (0x110e10246), source = 0x7fd03a755c60,
    run loops = <CFArray 0x7fd03a5ed390 [0x10ee647b0]>{type = mutable-small, count = 2, values = (
	0 : <0x7fd03a71a780>
	1 : <0x7fd03a4ae530>
)},
    context = <SocketStream@0x7fd03a62e9b0> { fd 13 }}, properties = 0x7fd03a621b70 }}
)}}
	2 : <CFRunLoopSource 0x7fd03a755c60 [0x10ee647b0]>{signalled = No, valid = Yes, order = 0, context = <CFSocket 0x7fd03a75d610 [0x10ee647b0]>{valid = Yes, type = 1, socket = 13, socket set count = 2,
    callback types = 0xd, callout = _ZN12SocketStream22_SocketCallBack_streamEP10__CFSocketmPK8__CFDataPKvPv (0x110e10246), source = 0x7fd03a755c60,
    run loops = <CFArray 0x7fd03a5ed390 [0x10ee647b0]>{type = mutable-small, count = 2, values = (
	0 : <0x7fd03a71a780>
	1 : <0x7fd03a4ae530>
)},
    context = <SocketStream@0x7fd03a62e9b0> { fd 13 }}}
}
,
modes = <CFBasicHash 0x7fd03a4ae630 [0x10ee647b0]>{type = mutable set, count = 2,
entries =>
	0 : <CFRunLoopMode 0x7fd03a4ae850 [0x10ee647b0]>{name = kCFRunLoopCommonModes, port set = 0x6d03, timer port = 0x6e03, 
	sources0 = (null),
	sources1 = (null),
	observers = (null),
	timers = (null),
	currently 467595065 (131896224716687) / soft deadline in: 1.84466122e+10 sec (@ -1) / hard deadline in: 1.84466122e+10 sec (@ -1)
},

	2 : <CFRunLoopMode 0x7fd03a4ae670 [0x10ee647b0]>{name = kCFRunLoopDefaultMode, port set = 0x6407, timer port = 0x6c03, 
	sources0 = <CFBasicHash 0x7fd03a4a5d10 [0x10ee647b0]>{type = mutable set, count = 2,
entries =>
	0 : <CFRunLoopSource 0x7fd03a4a24a0 [0x10ee647b0]>{signalled = No, valid = Yes, order = 0, context = <CFArray 0x7fd03a4a5b00 [0x10ee647b0]>{type = mutable-small, count = 2, values = (
	0 : <CFReadStream 0x7fd03a618c30>{<SocketStream 0x7fd03a618c30>{flags = 0x7fd03a62eaa8, read = 0x7fd03a618c30, write = 0x7fd03a617080, socket = <CFSocket 0x7fd03a75d610 [0x10ee647b0]>{valid = Yes, type = 1, socket = 13, socket set count = 2,
    callback types = 0xd, callout = _ZN12SocketStream22_SocketCallBack_streamEP10__CFSocketmPK8__CFDataPKvPv (0x110e10246), source = 0x7fd03a755c60,
    run loops = <CFArray 0x7fd03a5ed390 [0x10ee647b0]>{type = mutable-small, count = 2, values = (
	0 : <0x7fd03a71a780>
	1 : <0x7fd03a4ae530>
)},
    context = <SocketStream@0x7fd03a62e9b0> { fd 13 }}, properties = 0x7fd03a621b70 }}
	1 : <CFWriteStream 0x7fd03a617080>{<SocketStream 0x7fd03a617080>{flags = 0x7fd03a62eaa8, read = 0x7fd03a618c30, write = 0x7fd03a617080, socket = <CFSocket 0x7fd03a75d610 [0x10ee647b0]>{valid = Yes, type = 1, socket = 13, socket set count = 2,
    callback types = 0xd, callout = _ZN12SocketStream22_SocketCallBack_streamEP10__CFSocketmPK8__CFDataPKvPv (0x110e10246), source = 0x7fd03a755c60,
    run loops = <CFArray 0x7fd03a5ed390 [0x10ee647b0]>{type = mutable-small, count = 2, values = (
	0 : <0x7fd03a71a780>
	1 : <0x7fd03a4ae530>
)},
    context = <SocketStream@0x7fd03a62e9b0> { fd 13 }}, properties = 0x7fd03a621b70 }}
)}}
	2 : <CFRunLoopSource 0x7fd03a755c60 [0x10ee647b0]>{signalled = No, valid = Yes, order = 0, context = <CFSocket 0x7fd03a75d610 [0x10ee647b0]>{valid = Yes, type = 1, socket = 13, socket set count = 2,
    callback types = 0xd, callout = _ZN12SocketStream22_SocketCallBack_streamEP10__CFSocketmPK8__CFDataPKvPv (0x110e10246), source = 0x7fd03a755c60,
    run loops = <CFArray 0x7fd03a5ed390 [0x10ee647b0]>{type = mutable-small, count = 2, values = (
	0 : <0x7fd03a71a780>
	1 : <0x7fd03a4ae530>
)},
    context = <SocketStream@0x7fd03a62e9b0> { fd 13 }}}
}
,
	sources1 = <CFBasicHash 0x7fd03a4a5de0 [0x10ee647b0]>{type = mutable set, count = 0,
entries =>
}
,
	observers = (null),
	timers = (null),
	currently 467595065 (131896224728706) / soft deadline in: 1.84466122e+10 sec (@ -1) / hard deadline in: 1.84466122e+10 sec (@ -1)
},

}
}
)
```

I noticed it is running in with `current mode = kCFRunLoopDefaultMode`, but even replacing all the references of `kCFRunLoopDefaultMode` and `NSDefaultRunLoopMode` to `kCFRunLoopCommonModes` and `NSRunLoopCommonModes` respectively, I can't make this work.

It is important to notice I am using a fork of your project that has been updated to Swift 2.0, but I don't think this should make any difference. I also tried making `runLoop` as a blind attempt to solve the problem, but optional unwrapping is obviously not the cause for this.

Screenshot for context:
<img width="759" alt="screen shot 2015-10-27 at 00 28 36" src="https://cloud.githubusercontent.com/assets/2136642/10745510/ac29c258-7c42-11e5-96c2-b17c86e4b8db.png">

**Comment by kgreenek** [comment]
Hmm that's a really tough problem to debug. Changing the mode shouldn't
matter.

One common cause of this is if you try to update a UI element from a
background thread.

Looking at the code in the PeerConnection, I think I see the problem. It
doesn't actually dispatch on the delegateQueue when making calls to the
delegate, so your code might be getting called on a background thread when
you don't expect it to. Will take a look tonight when I get home and see if
I can push a quick fix :)

As a work-around, you can make sure that in any callbacks from the
PeerConnection, you dispatch to the main queue before updating any UI
elements.

**Comment by kgreenek** [comment]
Oof, supporting swift2 syntax is going to require a bit of work, and I need
to do that first. Standby...

**Comment by kgreenek** [comment]
OK I pushed a few big patches to update to swift2 (so you shouldn't need
your fork anymore), and also to fix the issue you were having. Let me know
if that works.

Cheers,
Kevin

**Comment by brunophilipe** [comment]
Hey. Thanks for the updates, that's awesome! It did not fix the problem for me, though. However, I think it is because of the "hackish" changes I made to support Vertcoin. When I changed all the parameters back to Bitcoin, the problem seem to disappear. I will close this for now, and in case I find anything, I open it again. :)
